"""AI vs Human Code Detector.

This module uses statistical heuristics to estimate whether code in a commit
was likely written by a human or generated by an AI tool.

IMPORTANT DISCLAIMER: This is a probabilistic mirror for self-reflection only.
It is NOT accurate enough to judge others. Do not use this to evaluate teammates,
grade students, or make employment decisions. The signals are imperfect by design.
Treat the output as a personal wellness metric, nothing more.
"""

import math
import re
import statistics
import uuid
from collections import Counter
from pathlib import Path
from typing import Optional

from pydantic import BaseModel
from rich.console import Console
from rich.progress import (
    BarColumn,
    MofNCompleteColumn,
    Progress,
    SpinnerColumn,
    TextColumn,
    TimeElapsedColumn,
)

console = Console()

# ── Constants ───────────────────────────────────────────────────────

CONVENTIONAL_PATTERN = re.compile(
    r"^(feat|fix|chore|refactor|docs|style|test|perf|ci|build)"
    r"(\(.+\))?!?:\s.{5,}"
)

HUMAN_MESSAGE_KEYWORDS = {
    "fixme", "todo", "why", "wtf", "finally", "ok", "test",
}

# ── Baseline Model ──────────────────────────────────────────────────

class PersonalBaseline(BaseModel):
    """Calibrated baseline metrics for a specific developer."""

    avg_lines_per_commit: float
    avg_velocity: float
    uses_conventional_commits: bool
    uses_autoformatter: bool
    typical_session_length: float


# ── AIDetector ──────────────────────────────────────────────────────


class AIDetector:
    """Classifies git commits as human-written, AI-generated, or uncertain.

    Uses a weighted ensemble of 5 statistical signals:

    ========== ====== =========================================
    Signal     Weight Logic
    ========== ====== =========================================
    velocity   0.30   lines added per minute
    burstiness 0.25   coefficient of variation of line lengths
    formatting 0.20   ratio of "cleanly formatted" lines
    message    0.15   commit message pattern analysis
    entropy    0.10   Shannon entropy of character frequencies
    ========== ====== =========================================

    Classification thresholds:
        - ``ai_probability >= 0.62`` → ``"ai"``
        - ``ai_probability <= 0.38`` → ``"human"``
        - otherwise → ``"uncertain"``
    """

    SIGNAL_WEIGHTS: dict[str, float] = {
        "velocity": 0.30,
        "burstiness": 0.25,
        "formatting": 0.20,
        "message": 0.15,
        "entropy": 0.10,
    }

    # ── Public API ──────────────────────────────────────────────────

    def analyze(self, commit: dict, baseline: Optional[PersonalBaseline] = None) -> dict:
        """Compute all 5 signal scores and classify a single commit.

        The original commit dict is returned with these fields added:
        ``ai_probability``, ``classification``, ``velocity_score``,
        ``burstiness_score``, ``formatting_score``, ``message_score``,
        ``entropy_score``.

        Args:
            commit: A commit dict from GitScanner matching the data
                contract (must have ``additions``, ``minutes_since_prev``,
                ``diff_text``, ``message`` at minimum).
            baseline: Optional PersonalBaseline object for calibrating thresholds.

        Returns:
            The same dict with AI detection fields added.
        """
        diff_text = commit.get("diff_text", "")
        added_lines = self._extract_added_lines(diff_text)

        # Baseline & Session Context Fix
        if "session_velocity" in commit:
            session_velocity_val = commit["session_velocity"]
            adds = commit.get("session_additions", 0)
        else:
            adds = commit.get("additions", 0)
            mins = commit.get("minutes_since_prev", 0.5)
            session_velocity_val = adds / max(mins, 0.5)

        velocity = self._velocity_score(session_velocity_val, adds, baseline)
        burstiness = self._burstiness_score(added_lines)
        formatting = self._formatting_score(added_lines)
        message = self._message_score(commit.get("message", ""))
        entropy = self._entropy_score(added_lines)

        w_vel = self.SIGNAL_WEIGHTS["velocity"]
        w_burst = self.SIGNAL_WEIGHTS["burstiness"]
        w_fmt = self.SIGNAL_WEIGHTS["formatting"]
        w_msg = self.SIGNAL_WEIGHTS["message"]
        w_ent = self.SIGNAL_WEIGHTS["entropy"]

        is_squash = commit.get("is_squash", False)

        if baseline:
            if baseline.uses_conventional_commits:
                w_msg = 0.05
                # High score normally means conventional commit (AI). Since human
                # does it, invert the score so it reads as human.
                message = 1.0 - message

            if baseline.uses_autoformatter:
                w_fmt = 0.05

        if is_squash:
            w_vel = 0.05
            w_fmt = 0.05

        # Normalize weights
        total_w = w_vel + w_burst + w_fmt + w_msg + w_ent
        w_vel /= total_w
        w_burst /= total_w
        w_fmt /= total_w
        w_msg /= total_w
        w_ent /= total_w

        ai_probability = (
            w_vel * velocity
            + w_burst * burstiness
            + w_fmt * formatting
            + w_msg * message
            + w_ent * entropy
        )

        if is_squash:
            ai_probability = max(0.45, min(0.55, ai_probability))

        ai_probability = round(ai_probability, 4)

        if is_squash:
            classification = "uncertain"
        elif ai_probability >= 0.62:
            classification = "ai"
        elif ai_probability <= 0.38:
            classification = "human"
        else:
            classification = "uncertain"

        result = dict(commit)
        result.update(
            {
                "ai_probability": ai_probability,
                "classification": classification,
                "velocity_score": round(velocity, 4),
                "burstiness_score": round(burstiness, 4),
                "formatting_score": round(formatting, 4),
                "message_score": round(message, 4),
                "entropy_score": round(entropy, 4),
            }
        )
        return result

    def analyze_batch(self, commits: list[dict], baseline: Optional[PersonalBaseline] = None) -> list[dict]:
        """Analyze a batch of commits with a Rich progress bar.

        Args:
            commits: List of commit dicts from GitScanner.
            baseline: Optional PersonalBaseline object.

        Returns:
            List of analyzed commit dicts with AI detection fields.
        """
        if not commits:
            return []

        results: list[dict] = []

        with Progress(
            SpinnerColumn(),
            TextColumn("[bold cyan]Analyzing commits"),
            BarColumn(),
            MofNCompleteColumn(),
            TimeElapsedColumn(),
            console=console,
            transient=True,
        ) as progress:
            task = progress.add_task("Analyzing", total=len(commits))
            for commit in commits:
                results.append(self.analyze(commit, baseline))
                progress.advance(task)

        # Summary line
        human = sum(1 for r in results if r["classification"] == "human")
        ai = sum(1 for r in results if r["classification"] == "ai")
        uncertain = sum(
            1 for r in results if r["classification"] == "uncertain"
        )
        console.print(
            f"[green]Analysis complete:[/green] "
            f"{human} human, {ai} AI, {uncertain} uncertain"
        )
        return results

    def get_summary_stats(self, analyzed_commits: list[dict]) -> dict:
        """Compute aggregate statistics over analyzed commits.

        Args:
            analyzed_commits: List of commit dicts that have already
                been run through ``analyze()`` or ``analyze_batch()``.

        Returns:
            Dict with keys: ``total``, ``human_count``, ``ai_count``,
            ``uncertain_count``, ``human_ratio``, ``avg_ai_probability``,
            ``monthly_breakdown``.
        """
        total = len(analyzed_commits)
        if total == 0:
            return {
                "total": 0,
                "human_count": 0,
                "ai_count": 0,
                "uncertain_count": 0,
                "human_ratio": 0.0,
                "avg_ai_probability": 0.0,
                "monthly_breakdown": {},
            }

        human_count = sum(
            1 for c in analyzed_commits if c["classification"] == "human"
        )
        ai_count = sum(
            1 for c in analyzed_commits if c["classification"] == "ai"
        )
        uncertain_count = sum(
            1 for c in analyzed_commits
            if c["classification"] == "uncertain"
        )
        avg_prob = sum(
            c["ai_probability"] for c in analyzed_commits
        ) / total

        # Monthly breakdown: "YYYY-MM" → {human, ai, uncertain}
        monthly: dict[str, dict[str, int]] = {}
        for commit in analyzed_commits:
            ts = commit.get("timestamp")
            if ts is not None:
                key = ts.strftime("%Y-%m")
            else:
                key = "unknown"

            if key not in monthly:
                monthly[key] = {"human": 0, "ai": 0, "uncertain": 0}
            monthly[key][commit["classification"]] += 1

        return {
            "total": total,
            "human_count": human_count,
            "ai_count": ai_count,
            "uncertain_count": uncertain_count,
            "human_ratio": round(human_count / total, 4),
            "avg_ai_probability": round(avg_prob, 4),
            "monthly_breakdown": dict(sorted(monthly.items())),
        }

    # ── Signal implementations ──────────────────────────────────────

    @staticmethod
    def _velocity_score(
        lpm: float, additions: int, baseline: Optional[PersonalBaseline] = None
    ) -> float:
        """Signal 1: coding velocity (lines added per minute).

        High velocity suggests AI-assisted code generation.
        Uses baseline threshold calibration.

        Args:
            lpm: Lines added per minute for this commit's session.
            additions: Raw number of additions to filter out tiny fixes.
            baseline: Optional PersonalBaseline.

        Returns:
            Score from 0.0 (definitely human pace) to 1.0 (definitely AI pace).
        """
        # Tiny commits are almost always human fixes
        if additions < 5:
            return 0.2

        base_10 = 10.0
        base_40 = 40.0
        base_80 = 80.0

        if baseline and baseline.avg_velocity > 40.0:
            scale = baseline.avg_velocity / 40.0
            base_10 *= scale
            base_40 *= scale
            base_80 *= scale

        if lpm >= base_80:
            return 0.95
        if lpm >= base_40:
            return 0.75 + (lpm - base_40) / (base_80 - base_40) * (0.95 - 0.75)
        if lpm >= base_10:
            return 0.50 + (lpm - base_10) / (base_40 - base_10) * (0.75 - 0.50)
        return 0.05 + (lpm / base_10) * (0.50 - 0.05)

    @staticmethod
    def _burstiness_score(added_lines: list[str]) -> float:
        """Signal 2: coefficient of variation of line lengths.

        AI-generated code tends to have very uniform line lengths
        (low CV), while human code is more variable (high CV).

        Args:
            added_lines: List of added source lines (without leading +).

        Returns:
            Score from 0.0 (chaotic/human) to 1.0 (uniform/AI).
        """
        if len(added_lines) < 5:
            return 0.5

        lengths = [len(line) for line in added_lines]
        n = len(lengths)
        mean = sum(lengths) / n
        variance = sum((x - mean) ** 2 for x in lengths) / n
        std = math.sqrt(variance)
        cv = std / (mean + 1e-9)

        if cv < 0.20:
            return 0.85
        if cv <= 0.40:
            # Linear: 0.20→0.85, 0.40→0.50
            return 0.85 - (cv - 0.20) / (0.40 - 0.20) * (0.85 - 0.50)
        if cv <= 0.70:
            # Linear: 0.40→0.50, 0.70→0.15
            return 0.50 - (cv - 0.40) / (0.70 - 0.40) * (0.50 - 0.15)
        return 0.10

    @staticmethod
    def _formatting_score(added_lines: list[str]) -> float:
        """Signal 3: ratio of 'cleanly formatted' lines.

        AI tools produce very consistently formatted code. Human code
        often has trailing whitespace, mixed indent styles, etc.

        A line is "clean" if:
        - Indentation uses consistent multiples of 2 or 4 spaces (no mixed tabs)
        - No trailing whitespace
        - Length is between 1 and 120 characters

        Args:
            added_lines: List of added source lines.

        Returns:
            Score clamped to [0.1, 0.9].
        """
        if not added_lines:
            return 0.5

        clean_count = 0
        for line in added_lines:
            if not line:
                # Empty lines are considered "clean"
                clean_count += 1
                continue

            # Check trailing whitespace
            if line != line.rstrip():
                continue

            # Check line length (1–120)
            if len(line) > 120:
                continue

            # Check indentation: must be spaces only (no tabs), and
            # the leading space count must be a multiple of 2 or 4
            stripped = line.lstrip(" ")
            indent = len(line) - len(stripped)
            if "\t" in line[:indent + 1] if indent > 0 else "\t" in line[:1]:
                continue
            if indent > 0 and indent % 2 != 0:
                continue

            clean_count += 1

        ratio = clean_count / len(added_lines)
        # Clamp to [0.1, 0.9]
        return max(0.1, min(0.9, ratio))

    @staticmethod
    def _message_score(message: str) -> float:
        """Signal 4: commit message pattern analysis.

        Conventional-commit style messages with detailed descriptions
        are more likely AI-generated or AI-assisted.

        Args:
            message: The commit message string.

        Returns:
            Score indicating likelihood of AI-generated message.
        """
        msg = message.strip()

        # Very short messages are almost certainly human
        if len(msg) < 4:
            return 0.05

        # Conventional commit with 5+ char description → likely AI-assisted
        if CONVENTIONAL_PATTERN.match(msg):
            return 0.75

        # Human frustration / shorthand markers
        msg_lower = msg.lower()
        for keyword in HUMAN_MESSAGE_KEYWORDS:
            if keyword in msg_lower:
                return 0.08

        # Default: ambiguous
        return 0.40

    @staticmethod
    def _entropy_score(added_lines: list[str]) -> float:
        """Signal 5: Shannon entropy of character frequencies.

        AI-generated code tends to be more repetitive/boilerplate
        (lower entropy), while human code has more variety.

        Args:
            added_lines: List of added source lines.

        Returns:
            Score from 0.0 to 1.0 (higher = more likely AI).
        """
        text = "\n".join(added_lines)
        if len(text) < 10:
            return 0.5

        freq = Counter(text)
        total_chars = len(text)
        entropy = 0.0
        for count in freq.values():
            p = count / total_chars
            if p > 0:
                entropy -= p * math.log2(p)

        # H > 4.8: likely minified/compressed, skip (return 0.5)
        if entropy > 4.8:
            return 0.5

        # H 3.8–4.8: linear scale → 0.3–0.7
        if entropy >= 3.8:
            return 0.3 + (entropy - 3.8) / (4.8 - 3.8) * (0.7 - 0.3)

        # H 3.2–3.8: linear → 0.8–0.3 (lower entropy = more AI-like)
        if entropy >= 3.2:
            return 0.8 - (entropy - 3.2) / (3.8 - 3.2) * (0.8 - 0.3)

        # H < 3.2: very low entropy = repetitive boilerplate = AI
        return 0.8

    # ── Helpers ─────────────────────────────────────────────────────

    @staticmethod
    def _extract_added_lines(diff_text: str) -> list[str]:
        """Extract added lines from a diff text.

        Lines starting with ``+`` (but not ``+++``) are treated as
        additions. The leading ``+`` is stripped.

        Args:
            diff_text: Raw diff text (may already be pre-filtered by
                GitScanner to contain only added lines without the +).

        Returns:
            List of added line strings.
        """
        lines: list[str] = []
        for line in diff_text.splitlines():
            if line.startswith("+") and not line.startswith("+++"):
                lines.append(line[1:])
            elif not line.startswith("-") and not line.startswith("@@"):
                # GitScanner pre-strips the '+', so these are raw added lines
                lines.append(line)
        return lines

    # ── Session & Baseline ──────────────────────────────────────────

    def group_into_sessions(self, commits: list[dict], gap_minutes: float = 45.0) -> list[list[dict]]:
        """Group commits where gap between consecutive commits < gap_minutes into sessions.
        
        Assigns session_id, session_duration, session_additions, and session_velocity
        to each commit dict in the list.
        """
        if not commits:
            return []

        sorted_commits = sorted(commits, key=lambda c: c["timestamp"])
        sessions = []
        current_session = []

        for commit in sorted_commits:
            if not current_session:
                current_session.append(commit)
                continue

            prev_commit = current_session[-1]
            diff = commit["timestamp"] - prev_commit["timestamp"]
            gap = diff.total_seconds() / 60.0

            if gap < gap_minutes:
                current_session.append(commit)
            else:
                sessions.append(current_session)
                current_session = [commit]

        if current_session:
            sessions.append(current_session)

        # Enrich commits
        for sess in sessions:
            sess_id = uuid.uuid4().hex
            
            if len(sess) > 1:
                duration_min = (sess[-1]["timestamp"] - sess[0]["timestamp"]).total_seconds() / 60.0
            else:
                duration_min = max(sess[0].get("minutes_since_prev", 0.5), 0.5)

            duration_min = max(duration_min, 0.5)
            sess_additions = sum(c.get("additions", 0) for c in sess)
            sess_velocity = sess_additions / duration_min

            for c in sess:
                c["session_id"] = sess_id
                c["session_duration"] = duration_min
                c["session_additions"] = sess_additions
                c["session_velocity"] = sess_velocity

        return sessions

    def build_baseline(self, commits: list[dict], repo_path: str) -> PersonalBaseline:
        """Build the PersonalBaseline from the developer's earliest 30 commits."""
        sorted_commits = sorted(commits, key=lambda c: c["timestamp"])
        first_30 = sorted_commits[:30]

        if not first_30:
            return PersonalBaseline(
                avg_lines_per_commit=0.0,
                avg_velocity=0.0,
                uses_conventional_commits=False,
                uses_autoformatter=False,
                typical_session_length=0.0,
            )

        velocities = [
            c["additions"] / max(c.get("minutes_since_prev", 0.5), 0.5)
            for c in first_30 if c.get("additions", 0) > 0
        ]
        avg_velocity = statistics.median(velocities) if velocities else 0.0

        conv_commits = sum(
            1 for c in first_30
            if re.match(r"^(feat|fix|chore|refactor|docs|style|test|perf|ci|build)(\(.+\))?!?:\s", c.get("message", ""))
        )
        uses_conventional_commits = (conv_commits / len(first_30)) > 0.5

        uses_autoformatter = False
        repo_dir = Path(repo_path)
        if repo_dir.exists():
            for fmt_file in [".ruff.toml", ".prettierrc", ".eslintrc", ".black"]:
                if (repo_dir / fmt_file).exists():
                    uses_autoformatter = True
                    break

            if not uses_autoformatter and (repo_dir / "pyproject.toml").exists():
                try:
                    content = (repo_dir / "pyproject.toml").read_text()
                    if "[tool.ruff]" in content:
                        uses_autoformatter = True
                except Exception:
                    pass

        avg_lines = sum(c.get("additions", 0) for c in first_30) / len(first_30)

        sessions = self.group_into_sessions(first_30)
        session_lengths = []
        for sess in sessions:
            if len(sess) > 1:
                dur = (sess[-1]["timestamp"] - sess[0]["timestamp"]).total_seconds() / 3600.0
            else:
                dur = 0.5
            session_lengths.append(dur)
            
        typ_session_len = statistics.mean(session_lengths) if session_lengths else 0.5

        return PersonalBaseline(
            avg_lines_per_commit=avg_lines,
            avg_velocity=avg_velocity,
            uses_conventional_commits=uses_conventional_commits,
            uses_autoformatter=uses_autoformatter,
            typical_session_length=typ_session_len,
        )
